# Generated by Django 5.2.6 on 2026-08-25 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0004_room_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField(help_text='เลือกวันใดก็ได้ในเดือนที่ต้องการออกบิล')),
                ('due_date', models.DateField()),
                ('room_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_start_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_current_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_start_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_current_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('internet_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('OVERDUE', 'ค้างชำระ'), ('PENDING_VERIFICATION', 'รอตรวจสอบการโอนเงิน'), ('PAID', 'ชำระเงินแล้ว')], default='OVERDUE', max_length=24)),
                ('payment_slip', models.ImageField(blank=True, null=True, upload_to='payment_slips/%Y/%m/')),
                ('slip_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='rooms.room')),
            ],
            options={
                'ordering': ['-billing_month', 'room__room_number'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.bill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('room', 'billing_month'), name='uq_bill_room_month'),
        ),
    ]
