# Generated by Django 5.2.6 on 2025-09-30 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('VACANT', 'VACANT'), ('OCCUPIED', 'OCCUPIED')], default='VACANT', max_length=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('floor', models.IntegerField(default=1)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='dorms.dorm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dorm', 'room_number'), name='uq_room_per_dorm')],
            },
        ),
    ]
