# Generated by Django 5.2.6 on 2025-09-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenant_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='room',
            name='tenant_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('VACANT', 'ยังไม่จอง'), ('OCCUPIED', 'จองแล้ว')], default='VACANT', max_length=10),
        ),
    ]
