# Generated by Django 5.2.6 on 2025-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_tenant_address_room_tenant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
