# Generated by Django 5.2.6 on 2026-08-25 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_booking_date_room_move_in_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tenant_user',
            field=models.ForeignKey(blank=True, help_text='บัญชีผู้เช่าที่ใช้ดูบิลและส่งสลิป', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
