# Generated by Django 5.2.6 on 2026-08-25 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0004_room_tenant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('REQUEST', 'คำขอจากผู้ใช้'), ('INVITATION', 'คำเชิญจากแอดมิน')], max_length=12)),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('APPROVED', 'อนุมัติแล้ว'), ('REJECTED', 'ปฏิเสธแล้ว')], default='PENDING', max_length=12)),
                ('note', models.TextField(blank=True, help_text='รายละเอียดเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_requests', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
