# Generated by Django 5.2.6 on 2026-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrequest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
