# Generated by Django 5.2.6 on 2025-09-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.TextField(blank=True)),
                ('max_rooms', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
