# Generated by Django 5.2.6 on 2025-09-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dorms/'),
        ),
    ]
